### ISSUE TITLE
Execution hangs on windows

### ISSUE THREAD

**Issue by omar-k** [narkisr/nmap4j#2]
Hi,
I tried to run nmap4j on windows but the execution kept hanging without returning anything, on tracing the issue, I noticed the hang happened at execute method on NMapExecutor when trying to get error stream, my fast fix was to check if the application running on windows don't read error stream, as following:

```
            if( getOS().indexOf("Windows") == -1) {
                results.setErrors( convertStream( process.getErrorStream() ) ) ;
            } else {
                results.setErrors( "" ) ;
            }
```

I am running it on windows 7 enterprise with JRE 7.

 Not sure what the issue here, but it dose not seem from API part.

Thanks,
Omar

**Comment by narkisr** [comment]
Ok, so this means that on windows possible errors won't be listed? 

Maybe its related to nmap stderr process handling?

**Comment by omar-k** [comment]
With my above change I will not be able to tell what are the errors.

It could be as you said related how nmap handles stderr, not sure if anyone have faced same issue before.

**Comment by narkisr** [comment]
Since no progress has been made on this ill close it for now, if a fix is available ill be happy to review

Thanks

**Comment by ahmednrana** [comment]
I am also facing the same issue
