### ISSUE TITLE
Cannot resolve setTrace() method in NMapXmlHandler.java

### ISSUE THREAD

**Issue by amithkoujalgi** [narkisr/nmap4j#4]
Cannot resolve` setTrace()` method in` org.nmap4j.parser.NMapXmlHandler.java` due to missing Trace definition in Host class.
```
		if(qName.equals(Trace.TRACE_TAG)) {
			trace = runHandler.createTrace(attributes);
			host.setTrace(trace);
		}
```

Add the following code in `org.nmap4j.data.nmaprun.Host.java` to resolve:

```
    private Trace trace;
    public Trace getTrace() {
        return trace;
    }

    public void setTrace(Trace trace) {
        this.trace = trace;
    }
```

**Comment by narkisr** [comment]
Ok, can you please create a pull request for this? 

Thanks

**Comment by amithkoujalgi** [comment]
Done. https://github.com/narkisr/nmap4j/pull/5

**Comment by narkisr** [comment]
Merged, thanks!
